ALTER TABLE "Route"
ADD COLUMN "commonRoad" TEXT NOT NULL DEFAULT '',
ADD COLUMN "routePolyline" TEXT NOT NULL DEFAULT '',
ADD COLUMN "borderCheckpointName" TEXT NOT NULL DEFAULT '',
ADD COLUMN "borderCheckpointLatitude" DOUBLE PRECISION,
ADD COLUMN "borderCheckpointLongitude" DOUBLE PRECISION,
ADD COLUMN "travelAdvisory" TEXT NOT NULL DEFAULT '',
ADD COLUMN "landmarkMarkers" JSONB NOT NULL DEFAULT '[]',
ADD COLUMN "trafficStatus" TEXT NOT NULL DEFAULT '',
ADD COLUMN "trafficDelayMinutes" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "Trip"
ADD COLUMN "pickupLatitude" DOUBLE PRECISION,
ADD COLUMN "pickupLongitude" DOUBLE PRECISION,
ADD COLUMN "dropoffLatitude" DOUBLE PRECISION,
ADD COLUMN "dropoffLongitude" DOUBLE PRECISION;
